reviews:
  path_filters:
    - '!dev/**'
    - '!examples/skills/**'
    - '!examples/configs/**'
    - '!BACKLOG.md'
    - '!BUILD.md'
    - '!AUDIT-PROMPT.md'
    - '!AUDIT-PROMPT-FULL.md'
    - '!CLAUDE.md'
    - '!CHANGELOG.md'
